[plugin]
repository = "https://github.com/RokasKil/TitleEdit.git"
commit = "764114be644d69f985750aa5d94dfb709c62ac16"
owners = [
    "RokasKil",
]
project_path = "TitleEdit"
changelog = """
- API12 and 7.2 patch update
"""
