[plugin]
repository = "https://github.com/RulHolos/Bartender.git"
commit = "9befd787eacee365600c22d72b3535387e26cd86"
owners = ["RulHolos"]
project_path = "Bartender"
changelog = """
# v1.1.6.1

- Fixed an issue with command arguments not working
- Added an alias "level" to the "lvl" argument
"""
