[plugin]
repository = "https://github.com/AtaeKurri/Bartender.git"
commit = "cccb027b4b0e0335451545b98148b6be3d6961f7"
owners = ["RulHolos"]
project_path = "Bartender"
changelog = """
# v1.1.3

- Push for 7.1
"""
